## dataRefine.py

# 1. Daily Window 정리

datas = [
    {'Policy Name': 'CYBER2013_FILE'},
    {'Policy Type': 'MS-Windows'},
    {'Active': 'no'},
    {'Effective date': '02/05/2013 16'},
    {'Backup network drvs': 'no'},
    {'Collect TIR info': 'no'},
    {'Mult. Data Streams': 'no'},
    {'Client Encrypt': 'no'},
    {'Checkpoint': 'no'},
    {'Policy Priority': '0'},
    {'Max Jobs/Policy': 'Unlimited'},
    {'Disaster Recovery': '0'},
    {'Collect BMR info': 'no'},
    {'Residence': 'stu_disk_nb5250'},
    {'Volume Pool': 'NetBackup'},
    {'Server Group': 'Any'},
    {'Keyword': '(none specified)'},
    {'Data Classification': '-'},
    {'Residence is Storage Lifecycle Policy': 'no'},
    {'Application Discovery': 'no'},
    {'Discovery Lifetime': '0 seconds'},
    {'ASC Application and attributes': '(none defined)'},
    {'Granular Restore Info': 'no'},
    {'Ignore Client Direct': 'no'},
    {'Use Accelerator': 'yes'},
    {'Optimized Backup': 'no'},
    {'HW/OS/Client': 'Windows-x86   Windows2003   030-ace-cyber'},
    {'Include:': 'C:\\'},
    'D:\\',
    {'Schedule': 'FULL'},
    {'Type': 'Full Backup'},
    {'Frequency': 'every 1 day'},
    {'Synthetic': '0'},
    {'Checksum Change Detection': '0'},
    {'PFI Recovery': '0'},
    {'Maximum MPX': '1'},
    {'Retention Level': '3 (1 month)'},
    {'Number Copies': '1'},
    {'Fail on Error': '0'},
    {'Residence': '(specific storage unit not required)'},
    {'Volume Pool': '(same as policy volume pool)'},
    {'Server Group': '(same as specified for policy)'},
    {'Residence is Storage Lifecycle Policy': '0'},
    {'Daily Windows': ''},
    'Sunday     01:00:00  -->  Sunday     04:00:00',
    'Monday     01:00:00  -->  Monday     04:00:00',
    'Tuesday    01:00:00  -->  Tuesday    04:00:00',
    'Wednesday  01:00:00  -->  Wednesday  04:00:00',
    'Thursday   01:00:00  -->  Thursday   04:00:00',
    'Friday     01:00:00  -->  Friday     04:00:00',
    'Saturday   01:00:00  -->  Saturday   04:00:00',
    {'Schedule': 'FULL'},
    {'Type': 'Full Backup'},
    {'Frequency': 'every 1 day'},
    {'Synthetic': '0'},
    {'Checksum Change Detection': '0'},
    {'PFI Recovery': '0'},
    {'Maximum MPX': '1'},
    {'Retention Level': '3 (1 month)'},
    {'Number Copies': '1'},
    {'Fail on Error': '0'},
    {'Residence': '(specific storage unit not required)'},
    {'Volume Pool': '(same as policy volume pool)'},
    {'Server Group': '(same as specified for policy)'},
    {'Residence is Storage Lifecycle Policy': '0'},
    {'Daily Windows': ''},
    'Sunday     01:00:00  -->  Sunday     04:00:00',
    'Monday     01:00:00  -->  Monday     04:00:00',
    'Tuesday    01:00:00  -->  Tuesday    04:00:00',
    'Wednesday  01:00:00  -->  Wednesday  04:00:00',
    'Thursday   01:00:00  -->  Thursday   04:00:00',
    'Friday     01:00:00  -->  Friday     04:00:00',
    'Saturday   01:00:00  -->  Saturday   04:00:00'
]

def daily_windows_refine(data_param):
    print(data_param)


daily_windows_refine(datas)